server:
  port: 8080

spring:
  application:
    name: service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      label: main
      username: admin
      password: 1234
