server:
  port: 8080

management:
  endpoint:
    shutdown:
      enabled: true

    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health, info, shutdown, refresh

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
